name: Test Plugin

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: PHP Unit Test
    strategy:
      matrix:
        php: [ '7.2', '7.4', '8.1' ] # PHP versions to check.
        wp: [ 'latest', '5.9' ]      # WordPress version to check.
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  lint:
    name: PHP Syntax Check
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.0

  php-lint:
    name: PHP Syntax Check for Plugin Directory
    uses: tarosky/workflows/.github/workflows/phplint.yml@main
    with:
      php_versions: '["7.2", "8.0", "8.2"]'

  assets:
    name: Check JS and CSS syntax
    uses: tarosky/workflows/.github/workflows/npm.yml@main
    with:
      node_version: 20
      command: lint
      package: package

  status-check:
    name: Status Check
    if: always()
    runs-on: ubuntu-latest
    needs: [ test, lint, php-lint, assets ] # Remove test temporary.
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
